title: Junyi (Kevin) Ma
position:  Master student 
affiliation: Beijing Institute of Technology
email: junyi.ma@bit.edu.cn / 3120200365@bit.edu.cn
keywords: Localization and Mapping, Probabilistic Deep Learning, Robotics.
google_scholar: https://scholar.google.com/citations?user=61oHA0kAAAAJ&hl=zh-CN&oi=ao
github_link: https://github.com/BIT-MJY
avatar: ./assets/img/avatar.png
# google_analytics: UA-111540567-4
favicon: ./assets/img/favicon.png
favicon_dark: ./assets/img/favicon-dark.png
# description: The Minimal Light is a simple and elegant jekyll theme for academic personal homepage.
canonical: https://minimal-light.yyliu.net/
remote_theme: yaoyao-liu/minimal-light
enable_footnote: true
